version: "3.7"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - "3000:3000"

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
