version: "3.7"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
