version: "3.7"

services:
  app:
    build:
      dockerfile: dev.Dockerfile
      context: .
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
