version: "3.7"

services:
  app:
    build:
      dockerfile: ci.Dockerfile
      context: .
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.example
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
