version: "3.7"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
