name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [dev]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and run Docker Compose
        run: |
          docker-compose -f docker-compose.ci.yml build
          docker-compose -f docker-compose.ci.yml up -d

      - name: Run unit tests
        run: docker-compose -f docker-compose.ci.yml exec app npm run test

      - name: Run E2E tests
        run: docker-compose -f docker-compose.ci.yml exec app npm run test:e2e

      - name: Stop and remove Docker Compose containers
        run: docker-compose -f docker-compose.ci.yml down
