name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [dev]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Print Jest Configuration
        run: npx jest --showConfig

      - name: Start containers
        run: docker-compose -f "docker-compose.ci.yml" up -d --build

      - run: docker ps -a
      - run: docker

      - name: Lint code
        run: docker-compose -f "docker-compose.ci.yml" run app npm run lint

      - name: Format code
        run: docker-compose -f "docker-compose.ci.yml" run app npm run format

      - name: Setup Prisma
        run: docker-compose -f "docker-compose.ci.yml" run app npm run migrate:dev

      - name: Run unit tests
        run: docker-compose -f "docker-compose.ci.yml" run app npm run test:cov

      - name: Run E2E tests
        run: docker-compose -f "docker-compose.ci.yml" run app npm run test:e2e

      - name: Upload coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: ./coverage/lcov.info

      - name: pwd app
        run: docker-compose -f "docker-compose.ci.yml" run app pwd

      - name: Run ls
        run: docker-compose -f "docker-compose.ci.yml" run app ls

      - name: Run ls
        run: docker-compose -f "docker-compose.ci.yml" run app ls src

      - name: pwd
        run: pwd

      - name: not docker Run ls
        run: ls

      - name: pwd
        run: pwd

      - name: Run ls
        run: docker-compose -f "docker-compose.ci.yml" run app ls

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./coverage

      - name: Stop containers
        run: docker-compose -f "docker-compose.ci.yml" down
