name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [dev]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Print Jest Configuration
        run: npx jest --showConfig

      - name: Start containers
        run: docker-compose -f "docker-compose.ci.yml" up -d --build

      - run: docker ps -a
      - run: docker

      - name: Lint code
        run: docker-compose -f "docker-compose.ci.yml" run app npm run lint

      - name: Format code
        run: docker-compose -f "docker-compose.ci.yml" run app npm run format

      - name: Setup Prisma
        run: docker-compose -f "docker-compose.ci.yml" run app npm run migrate:dev

      - name: Run unit tests
        run: docker-compose -f "docker-compose.ci.yml" run app npm run test:cov

      - name: Run E2E tests
        run: docker-compose -f "docker-compose.ci.yml" run app npm run test:e2e

      - name: Run unit tests with coverage
        run: docker-compose -f "docker-compose.ci.yml" run app npm run test:cov

      - name: Run ls
        run: docker-compose -f "docker-compose.ci.yml" run app ls

      - name: Save coverage report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./coverage

      - name: Stop containers
        run: docker-compose -f "docker-compose.ci.yml" down
